### ISSUE TITLE
无法使用任何工作台

### ISSUE THREAD

**Issue by xiaomoDDJ** [GuizhanCraft/SlimeTinker-CN#12]
## 描述 (必须)
无法使用任何工作台

## 服务器日志 / 错误报告

[22:42:47 ERROR]: Could not pass "BlockBreakHandler" for RepairBench - 'TINKERS_REPAIR_BENCH' (SlimeTinker vBuild 7 zh-CN(ybw0014) (git 9ef7fee))
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Paper-785]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-785]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-785]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at io.github.sefiraat.slimetinker.infinitylib.machines.MenuBlock$1.onPlayerBreak(MenuBlock.java:47) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callBlockHandler$2(BlockListener.java:163) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:924) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:163) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:131) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor513.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-785]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-785]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-785]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:359) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-785]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-785]
	at java.lang.Thread.run(Thread.java:831) [?:?]

## 运行环境 (必须)

Slimefun-v4.9-canary-07af561.jar
PaperSpigot 1.16.5
Windous Server 2012

- Minecraft 版本: 1.16.5
- Slimefun 版本: Slimefun-v4.9-canary-07af561.jar
- SlimeTinker 版本:  SlimeTinker vBuild 7 zh-CN(ybw0014) (git 9ef7fee))

**Comment by ybw0014** [comment]
下载的jar不完整，请重新下载后再试

**Comment by xiaomoDDJ** [comment]
> 下载的jar不完整，请重新下载后再试

https://builds.guizhanss.net/ybw0014/SlimeTinker-CN/master/7
我用的是这个下载地址
下载到的jar包有829Kb
不应该不完整啊
